"""Single-class Grounding DINO teacher config for the apple detection study.

Required environment variables:
  GDINO_DATA_ROOT: original YOLO dataset root containing the images.
  GDINO_ANNOTATION_ROOT: directory containing COCO ``train.json`` and
    ``val.json`` generated by ``convert_yolo_to_coco.py``.

Optional variables:
  GDINO_MAX_EPOCHS (default 50), GDINO_BATCH_SIZE (default 1),
  GDINO_ACCUM_STEPS (default 16), GDINO_NUM_WORKERS (default 2),
  GDINO_SCALE (default ``800,1333``), GDINO_SMOKE_SAMPLES (default 0),
  GDINO_WEIGHTS (defaults to official Grounding DINO Swin-T checkpoint).
"""

import os


data_root = os.environ["GDINO_DATA_ROOT"]
annotation_root = os.environ["GDINO_ANNOTATION_ROOT"]
max_epochs = int(os.getenv("GDINO_MAX_EPOCHS", "50"))
batch_size = int(os.getenv("GDINO_BATCH_SIZE", "1"))
accumulative_counts = int(os.getenv("GDINO_ACCUM_STEPS", "16"))
num_workers = int(os.getenv("GDINO_NUM_WORKERS", "2"))
smoke_samples = int(os.getenv("GDINO_SMOKE_SAMPLES", "0"))
scale_h, scale_w = (int(value) for value in os.getenv("GDINO_SCALE", "800,1333").split(","))

# The official MMDetection checkout is kept alongside this repository as
# ``D:/Github Code/.tmp/mmdetection-v3.3.0``.  ``_base_`` is evaluated before
# Python variables/environment variables, so it must stay a literal relative
# path rather than use ``MMDET_ROOT``.
_base_ = "../../../.tmp/mmdetection-v3.3.0/configs/grounding_dino/grounding_dino_swin-t_finetune_16xb2_1x_coco.py"

load_from = os.getenv(
    "GDINO_WEIGHTS",
    "https://download.openmmlab.com/mmdetection/v3.0/grounding_dino/groundingdino_swint_ogc_mmdet-822d7e9d.pth",
)
class_name = ("apple",)
metainfo = dict(classes=class_name, palette=[(220, 20, 60)])
dataset_indices = smoke_samples if smoke_samples > 0 else None

model = dict(bbox_head=dict(num_classes=1))

train_pipeline = [
    dict(type="LoadImageFromFile", backend_args=_base_.backend_args),
    dict(type="LoadAnnotations", with_bbox=True),
    dict(type="RandomFlip", prob=0.5),
    dict(type="RandomChoiceResize", scales=[(scale_h, scale_w)], keep_ratio=True),
    dict(
        type="PackDetInputs",
        meta_keys=("img_id", "img_path", "ori_shape", "img_shape", "scale_factor", "flip", "flip_direction", "text", "custom_entities"),
    ),
]
test_pipeline = [
    dict(type="LoadImageFromFile", backend_args=_base_.backend_args),
    dict(type="FixScaleResize", scale=(scale_h, scale_w), keep_ratio=True),
    dict(type="LoadAnnotations", with_bbox=True),
    dict(
        type="PackDetInputs",
        meta_keys=("img_id", "img_path", "ori_shape", "img_shape", "scale_factor", "text", "custom_entities"),
    ),
]

train_dataloader = dict(
    batch_size=batch_size,
    num_workers=num_workers,
    persistent_workers=num_workers > 0,
    dataset=dict(
        data_root=str(data_root),
        metainfo=metainfo,
        ann_file=os.path.join(annotation_root, "train.json"),
        data_prefix=dict(img=""),
        filter_cfg=dict(filter_empty_gt=False),
        pipeline=train_pipeline,
        return_classes=True,
        indices=dataset_indices,
    ),
)
val_dataloader = dict(
    batch_size=1,
    num_workers=num_workers,
    persistent_workers=num_workers > 0,
    dataset=dict(
        data_root=str(data_root),
        metainfo=metainfo,
        ann_file=os.path.join(annotation_root, "val.json"),
        data_prefix=dict(img=""),
        pipeline=test_pipeline,
        return_classes=True,
        indices=dataset_indices,
        test_mode=True,
    ),
)
test_dataloader = val_dataloader
val_evaluator = dict(ann_file=os.path.join(annotation_root, "val.json"))
test_evaluator = val_evaluator

optim_wrapper = dict(
    _delete_=True,
    type="OptimWrapper",
    optimizer=dict(type="AdamW", lr=0.00005, weight_decay=0.0001),
    clip_grad=dict(max_norm=0.1, norm_type=2),
    accumulative_counts=accumulative_counts,
    paramwise_cfg=dict(
        custom_keys={
            "absolute_pos_embed": dict(decay_mult=0.0),
            "backbone": dict(lr_mult=0.1),
            "language_model": dict(lr_mult=0.0),
        }
    ),
)
param_scheduler = [
    dict(type="LinearLR", start_factor=0.001, by_epoch=False, begin=0, end=30),
    dict(type="MultiStepLR", begin=0, end=max_epochs, by_epoch=True, milestones=[max(1, int(max_epochs * 0.75))], gamma=0.1),
]
train_cfg = dict(max_epochs=max_epochs, val_interval=1 if smoke_samples == 0 else max_epochs + 1)
default_hooks = dict(
    checkpoint=dict(interval=1, max_keep_ckpts=2, save_best="coco/bbox_mAP"),
    logger=dict(type="LoggerHook", interval=5),
)
visualizer = dict(
    vis_backends=[
        dict(type="LocalVisBackend"),
        dict(type="TensorboardVisBackend"),
    ]
)
auto_scale_lr = dict(enable=False, base_batch_size=16)
